<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-ios</TargetFramework>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);MSB3539</NoWarn>
        <BaseOutputPath>bin\</BaseOutputPath>
        <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.iOS" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.Boilerplates.Avalonia\ImeSense.Boilerplates.Avalonia.csproj" />
    </ItemGroup>
</Project>
